import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private final String name;
    private final String[] args;

    private App (String[] args) {
        name = args.length > 0 ? args[0] : "";
        this.args = args.length > 1
            ? Arrays.copyOfRange(args, 1, args.length)
            : new String[] {};
    }

    public String invoke () {
        try {
            return CommandParser.parse(name, args).run();
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
    }

    public static void main (String[] args) {
        System.out.println(new App(args).invoke());
    }
}
